# SQLite Configuration
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.url=jdbc:sqlite:vehicle_registration.db
spring.datasource.username=
spring.datasource.password=

# Hibernate Configuration
spring.jpa.database-platform=com.github.gwenn.sqlite.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Disable connection pooling
spring.datasource.type=org.sqlite.SQLiteDataSource

# Thymeleaf Configuratioalse

spring.jpa.open-in-view=false